### ISSUE TITLE
adding bounds to data types causes UPER encoding to fail (range start index X out of range for slice of length Y)

### ISSUE THREAD

**Issue by achubbic-snav** [gabhijit/hampi#59]
Hello, I have found that attempting to uper encode primitive values (perhaps more complex structs too) causes an indexing error within mod.rs

Please find a minimal reproducible example below:

asn1 bindings:
```
#[derive(asn1_codecs_derive :: UperCodec, Debug)]
#[asn(type = "INTEGER", lb = "0", ub = "63")]
pub struct INTEGER_20(pub u8);
```

```
let mut data: PerCodecData = PerCodecData::new_uper();
let my_int: INTEGER_20 = INTEGER_20(3);
my_int.uper_encode(&mut data)?;
```

output:
```
thread 'main' panicked at 'range start index 125 out of range for slice of length 16', library/core/src/slice/index.rs:52:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
   2: core::slice::index::slice_start_index_len_fail_rt
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/slice/index.rs:52:5
   3: core::ops::function::FnOnce::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
   4: core::intrinsics::const_eval_select
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/intrinsics.rs:2696:5
   5: core::slice::index::slice_start_index_len_fail
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/slice/index.rs:42:9
   6: <core::ops::range::RangeFrom<usize> as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/slice/index.rs:390:13
   7: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/slice/index.rs:18:9
   8: core::array::<impl core::ops::index::Index<I> for [T; N]>::index
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/array/mod.rs:286:9
   9: asn1_codecs::per::common::encode::encode_internal::encode_constrained_whole_number_common
             at /Users/ayden.chubbic/.cargo/registry/src/github.com-1ecc6299db9ec823/asn1-codecs-0.5.1/src/per/common/encode/encode_internal.rs:128:26
  10: asn1_codecs::per::common::encode::encode_integer_common
             at /Users/ayden.chubbic/.cargo/registry/src/github.com-1ecc6299db9ec823/asn1-codecs-0.5.1/src/per/common/encode/mod.rs:88:13
  11: asn1_codecs::per::uper::encode::encode_integer
             at /Users/ayden.chubbic/.cargo/registry/src/github.com-1ecc6299db9ec823/asn1-codecs-0.5.1/src/per/uper/encode/mod.rs:74:5
  12: <generate_lpp::lpp_bindings::INTEGER_20 as asn1_codecs::per::uper::UperCodec>::uper_encode
             at ./src/lpp_bindings.rs:7924:10
  13: generate_lpp::load_lpp_data_into_file
             at ./src/main.rs:62:5
  14: generate_lpp::main
             at ./src/main.rs:22:5
  15: core::ops::function::FnOnce::call_once
             at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:248:5
```

NOTE: removal of `lb = "0", ub = "63"` resolves the immediate error, (encoding does not yield a panic), but subsequent decoding fails. e.g. running

```
let bytes = data.into_bytes();
let mut file = OpenOptions::new().write(true).open(filepath.as_path())?;

let decoded_bytes = std::fs::read(filepath)?;
let mut data: PerCodecData = PerCodecData::from_slice_uper(&decoded_bytes);
let msg = <bindings_file>::INTEGER_20::uper_decode(&mut data)?;
println!("msg contents: {}", msg.0);
```

yields inaccurate numbers

**Comment by gabhijit** [comment]
@achubbic-snav : Thanks for reporting this error. Will take a look. Looks like some edge case around the number 63 is not well handled. Is it possible to get the actual bitstream that gets `UPER` ecoded (perhaps using some other tools - or even a dump from packet)?. This would also help a lot. 

Thanks
